export const projects = [
  {
    id: "RRAE4Vj5j14CTrP6t70M",
    title: "Portfolio Website",
    description: "",
    images: [
      "https://res.cloudinary.com/devton/image/upload/v1711938109/portfolio/project-image/portfolioa_zhtwhc.png",
      "https://res.cloudinary.com/devton/image/upload/v1711938111/portfolio/project-image/portfoliob_ncbrsu.png",
      "https://res.cloudinary.com/devton/image/upload/v1711938108/portfolio/project-image/portfolioc_u3paf9.png",
    ],
    tags: ["ReactJS", "JavaScript", "Firebase (Data store)", "EmailJS"],
    url: "",
    github: "https://github.com/tonsisouvanh/devtons",
  },
  {
    id: "S5gIszjVZDnu86bzo6KT",
    title: "Lao Student Management System in HCM",
    description:
      "The web app built to manage Laos students that are currently studying in Ho Chi Minh City, Vietnam. It is a MERN stack web app.",
    images: [
      "https://res.cloudinary.com/devton/image/upload/v1711503866/portfolio/project-image/hcmstudent_r8ur5d.png",
      "https://res.cloudinary.com/devton/image/upload/v1711936676/portfolio/project-image/hcmstua_sdbcbp.png",
      "https://res.cloudinary.com/devton/image/upload/v1711936672/portfolio/project-image/hcmstub_q6sp6q.png",
      "https://res.cloudinary.com/devton/image/upload/v1711936670/portfolio/project-image/hcmstuc_qftpp1.png",
      "https://res.cloudinary.com/devton/image/upload/v1711936670/portfolio/project-image/hcmstud_rumiv6.png",
    ],
    tags: [
      "ReactJS",
      "HTML",
      "CSS",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose (ORM)",
      "Redux Toolkit",
    ],
    url: "",
    github: "https://github.com/tonsisouvanh/svlao-app",
  },
  {
    id: "TZexMnECRKzLg5s936FL",
    title: "SQL Server Integration System & SSAS",
    description: "",
    images: [],
    tags: [],
    url: "",
    github: "https://github.com/tonsisouvanh/SSIS-SSAS-BI09-Assignment",
  },
  {
    id: "ZUOiCog9JLPohEu2ECtg",
    title: "Vaccine Booking App",
    description:
      "The Vaccine Booking app is a university assignment project in Distributed Application subject.",
    images: [
      "https://res.cloudinary.com/devton/image/upload/v1664009586/portfolio/project-image/vaccine_01_gjhosi.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664009589/portfolio/project-image/vaccine_main_htsrdl.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664009586/portfolio/project-image/vaccine_02_mfsdvs.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664009588/portfolio/project-image/vaccine_03_u1puq0.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664009582/portfolio/project-image/vaccine_04_haqxe5.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664009583/portfolio-project-image/vaccine_05_mwrvoj.png",
    ],
    tags: [
      "ReactJS",
      "HTML",
      "CSS",
      "JS",
      "Node.js",
      "MongoDB",
      "Redux Toolkit",
    ],
    url: "",
    github: "https://github.com/tonsisouvanh/vaccine-registration-app",
  },
  {
    id: "ibG5a0ChEUytZHH8dbl3",
    title: "Cyberpunk Hub - Clothing Store Web App",
    description:
      "The Clothing store web app where customers can access the shop to see all the products. Customers can buy the product through the WhatsApp chat.",
    images: [],
    tags: ["ReactJS", "HTML", "CSS", "JS", "Node.js"],
    url: "",
    github: "https://github.com/tonsisouvanh/cyberpunk-hub",
  },
  {
    id: "4C5X3LRMR64eFKl9IVte",
    title: "Netflix Clone",
    description:
      "Netflix clone app built with React.js, Tailwind CSS, and the TMDB API. Features mobile and desktop responsive design using Tailwind CSS. Implements Firebase email and password authentication for login/signin. Retrieves movie data from the TMDB API.",
    images: [
      "https://res.cloudinary.com/devton/image/upload/v1645154746/portfolio/project-image/disney-plus-b_cwpk0v.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664005770/portfolio/project-image/netflix_02_kkgo0z.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664005778/portfolio/project-image/netflix_03_tvm1zo.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1664005772/portfolio/project-image/netflix_01_ld4qhy.png",
    ],
    tags: ["ReactJS", "TailwindCSS", "TMDB API", "Firebase"],
    url: "https://netflix-clone-devtons.web.app/",
    github: "https://github.com/tonsisouvanh/netflix-clone",
  },
  {
    id: "DSi90GkpYG9r4y5atZDu",
    title: "Car Repair Service",
    description:
      "It is a C# WinForm application with SQL Server as the database. This WinForm app was built for a car repair service owned by my friend.",
    images: [],
    tags: ["WinForm/WPF/.NET", "C#", "SQL Server"],
    url: "",
    github: "https://github.com/tonsisouvanh/Car-Repair-Service",
  },
  {
    id: "JMF4NHAq78fPBuYf9Mg9",
    title: "Disney Plus Clone",
    description:
      "Disney Plus clone app built with React.js, Styled Components, Firebase (Firestore & Authentication). Responsive UI, Firebase Google Authentication for login, and Firestore for movie data storage.",
    images: [
      "https://res.cloudinary.com/devton/image/upload/v1645154746/portfolio/project-image/disney-plus-a_zsms5i.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1645154746/portfolio/project-image/disney-plus-b_cwpk0v.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1645154746/portfolio/project-image/disney-plus-d_bsa7lg.png",
      "https://res.cloudinary.com/shoppin/image/upload/v1645154746/portfolio/project-image/disney-plus-c_pi5rde.png",
    ],
    tags: ["ReactJS", "Styled Components", "HTML", "CSS", "JS", "Firebase"],
    url: "https://disney-plus-clone-f3cf5.web.app/",
    github: "https://github.com/tonsisouvanh/disney-plus-clone",
  },
];
